### ISSUE TITLE
Question : what is the plan for gui/gui.ml ?

### ISSUE THREAD

**Issue by GuillaumeBrochu** [geneweb/geneweb_tmp#19]
I have discovered this interesting tool recently while working on the Debian package.

However, I have noticed some warnings during compilations (see https://github.com/geneweb/geneweb/issues/13) and I have also observed some execution bugs when testing it on Debian. I don't know if this changed in the last days, but few weeks ago, it was not compiled by default with the vanilla makefile.

My opinion, based on what I've read on the web forums about geneweb, is that this tool definitely satisfies a need for a "simpler use" of geneweb by users that are not familiar with command lines, daemons, scripts, and etc.

So the question is : do you consider that this gui tool is still part of Geneweb's future with version 7.0 and beyond? 

Should I put some time to test it further? Is it worth it?

Thank you!

**Comment by ipfix** [comment]
The GUI was released for the 6.06 version of GeneWeb on 04/12/2012. It is similar to launch but supposed to be a bit more up to date.

Also the warning are not important, but you closed #13 way too soon because it was not in the master. [Our man power is not very big, even if we propose some patch, the ticket must be closed only when the patch is merged into master or we can't follow what is a bug and what is just a wrong usage].

My opinion about the GUI is that it was supposed to answer the problems of running GeneWeb just like you described, also it did not receive a good reception as I expected because you need to install the graphical dependency to run the GUI and people didn't want this.

As about its future, I have no idea ! It depends on the feedback. It's up to you if you want to test it further, communicate about it, promote it ...

There are many tools inside GeneWeb that are not distributed with the "packaged version", and they are not removed, sometimes improved ... I don't think you should add all of them in your Debian package.

**Comment by GuillaumeBrochu** [comment]
Thank you for these clarifications.

I have reopened the issue in other to evaluate the other compilation warnings (there is at least one more warning to fix...). I closed it previously because I though they were just inoffensive warnings.

Regarding geneweb-gui, it is already in the Debian package (in the Debian git repo since December 2012, and currently in Stretch and Sid ), but I don't see it in Ubuntu:
https://packages.debian.org/sid/geneweb-gui
https://launchpad.net/ubuntu/+source/geneweb

I'll put some time to test this gui tool and try to figure out what's wrong with it (on my computer, with the Debian package)

**Comment by GuillaumeBrochu** [comment]
This week, I have taken time to test this tool and I like it A LOT. It's a really nice addition to geneweb for users that are not familiar with command line stuff. 

Actually, the bugs with the geneweb package (geneweb-gui) were mostly related to its integration with the path structure in Debian. I prepared a patch for this... should be available soon in Debian. It looks like this:
https://github.com/GuillaumeBrochu/geneweb/commits/tmp_20160402_fix_gui_for_Debian

Some of the changes in this patch could also be "PRed" to the upstream code (with some rework).

Furthermore, it would be nice to have a conditional compilation for this tool for the upcoming Geneweb7-beta

**Comment by mbouaziz** [comment]
All syntax fixes: https://github.com/mbouaziz/geneweb/commit/03f0753fa736b861633e0306e42a0fe31e3d3cf3

gui cannot be added to target 'all' right now because there are dependencies issues on Windows and Mac (cf continuous integration reports https://ci.appveyor.com/project/ipfix/geneweb/build/1.0.72 and https://travis-ci.org/geneweb/geneweb/builds/122984341), or it could be added only if the package lablgtk2 is found.

**Comment by GuillaumeBrochu** [comment]
WOW! :+1:

**Comment by GuillaumeBrochu** [comment]
https://github.com/geneweb/geneweb_tmp/commit/ceb0f7fee18fd18b925cdcfdf71b71a26ac125fc
